apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: hello-node-ssl-certs
data:
  tls.crt: MIIDoTCCAomgAwIBAgIJAPxBOrHijZObMA0GCSqGSIb3DQEBCwUAMBIxEDAOBgNVBAMMB0JvZ3VzQ0EwHhcNMTkwMzIwMDIyNzMyWhcNNDYwODA1MDIyNzMyWjBiMQswCQYDVQQGEwJVUzELMAkGA1UECAwCR0ExDzANBgNVBAcMBkNhbnRvbjEPMA0GA1UECgwGRm9vQmFyMQwwCgYDVQQLDANCYXAxFjAUBgNVBAMMDWZvb2Jhci5kb21haW4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDEGbH1gLreX7gBFRtci2xYuWaxg/w0FdBDh0Kdn48GNmWeuqV4tgB64Bp0ypG1+6uNwkB4fDVhqekqAVrWOGPlNWS7NsPsZ/fbvKT7fD5zBThQ8JcFffsLpPBkaRk1ahtqbFhDm8bS43q1OpY2qhCZnHY29UXpS15e21IFtINsPZ2z0KMyDEYk3upeHIXVHLznW8hc9SuToekvrQvwJNZdxguBKY6wLxsEqsM7THb6ZQmpLMhZd4h/y0fo6pzKPizh3283xkJqAWFJP9CHP5q/RWz2/p1Vs6hLFM58YrYJcDtNgXjZqWHqnAYq7tVQzCs33y0M304ixJubG3gXtZOTAgMBAAGjgakwgaYwQgYDVR0jBDswOYAUK/PnBklKovnkhfNtwtVmhTD0X9yhFqQUMBIxEDAOBgNVBAMMB0JvZ3VzQ0GCCQDPIDTxrW9aMDAJBgNVHRMEAjAAMAsGA1UdDwQEAwIEMDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwKQYDVR0RBCIwIIINZm9vYmFyLmRvbWFpboIPKi5mb29iYXIuZG9tYWluMA0GCSqGSIb3DQEBCwUAA4IBAQBBi5333rjfRtXz6jcfFn4TKt7mhXWV380zF0uIfFp62NriOKbNRwaeXUAHtYcCBS9oc3KaYTB1IE3RAqTkMWPqUx/ykjwiPplQ/KUwZF7wHGuuOxHkRug640T+odCx890TaoOwTS9iF709c4OMI90+1XemsNkz7T3rNIdTiBbXuEcy5pP74gjTdX9Oe3lyeynVlMn8j/eZRAk0FhamkO7XLOb1hMvcygyLOZLO+73i930h3jUaxjaTUBaMBv3PGg63kIXwzdkebzT2RXh7S09K6U+nftVlisqV0y2kyMCXXeGUNsuY6msG5bZ+U/7YJ0r8eDifQJQJLSZgIp4MN19G
  tls.key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDEGbH1gLreX7gBFRtci2xYuWaxg/w0FdBDh0Kdn48GNmWeuqV4tgB64Bp0ypG1+6uNwkB4fDVhqekqAVrWOGPlNWS7NsPsZ/fbvKT7fD5zBThQ8JcFffsLpPBkaRk1ahtqbFhDm8bS43q1OpY2qhCZnHY29UXpS15e21IFtINsPZ2z0KMyDEYk3upeHIXVHLznW8hc9SuToekvrQvwJNZdxguBKY6wLxsEqsM7THb6ZQmpLMhZd4h/y0fo6pzKPizh3283xkJqAWFJP9CHP5q/RWz2/p1Vs6hLFM58YrYJcDtNgXjZqWHqnAYq7tVQzCs33y0M304ixJubG3gXtZOTAgMBAAECggEAUNNWah3455cEPE36zRYaPieMkDYaSU2EXZDugBE33hOlptq/QRWi9QJRZTno/N0SRIeAEyj+x5ZEqC+OxSTQ57QuJIvaDSJ9InCKf60iAD5yi8neNUFLq+z7uCcpYL6vNhoZ9yPJuzpPZUsUhstptCatAtHtUs7hwq8bC4bvdDjoh5bIhd4RgYGhZPLDOEMu6BfW1dye6Ia8AOEEYFPkekVNdvOjusfGwOYWQhVvbT+OarMpWy+yKaGcMvh1O6t65DOveONVQdd1X1STKF7/+h2o5G4fqL/nPdSxDhIKqjIRqwUUmwNoiVCXI/L6NVg+CC1UIvRD4ISxDTeO086yYQKBgQDhDnVkcXW36ZlEU8kEmN7YFisOXsaBkeK5jxZp6NkA59i6rD7Mo1WgQFMXxDqW/qp1iK27z+Y6xJn0f/HlNkjDN3FCsSB2eaZGVSjDAL4+JxY2V/gM7KAzckWmdKWmntnU0dzbWwfk0xcyOOKqblxIMgO5AYMWYszsF1vvYicq5QKBgQDfEAoBQfJ9tQtRIzFsR+UeXreA4r3DeInOF0WlsWRHDbxqYUir2bcBc5aRpb0iQseyxiTc3QiNhQXTpqS1anq29yJIdaNGOPHqQHVY138fK9MkQN5q5CINL+MRtqjZA7u0Qxg0G0VftJp4PQL5G1pvqV16fHojnNu7Uv3Hwg1FFwKBgQCJ4UjMg7KCPUxYDxjNhzannlU8lZX6Fb2Yv3AU7MHeCyy9mP9UchDof+AoZGEc1uLp5RXDRaiggohrweMZ8Xr8lr/+AvSHgRn8Zvn1FkR3YYz7OEPQ7ztqqWzAgSBnh1SfTP+JKCka6LSCYVWE4t4IoROkyaddFKTFU75QV4r1fQKBgQCNWUONwnVgFS5jrvJtlC1rDkgoIwZu7F4eu36F3aAWqmyf2J/NTjv6bn2WM7ljEYAsGAVZ87KswwOLOAkdcKjscjRGSE07fXBGqavyrTO/0+yLB5QplgDB7HtuSRo70nLKas3WjwVp/S75TGgq5JttMJystl5LXOWckZ2BTMVN5wKBgQDWy+OedCxQtj8T5R7JNgyf6M7y5jdSuRaTKr3fVAX9MPFn4MaatlXZvB5KYC6JddemwkWdUilsP6i75/gFChkxFnTJOYSw4TIH268DMrTrQF+XyUSayO+KUpCc0G4rqSDq4fRyxujfEh5KKQvM+0/vbElXQyaBHmBBuGUuMWIgZw==
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-node
  name: hello-node-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-node
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-node-ingress
spec:
  tls:
  - secretName: hello-node-ssl-certs
  rules:
  # You may need to add this host to your hosts file if it isn't registered and pointing at your ingress IP
  - host: foobar.domain
    http:
      paths:
      - backend:
          serviceName: hello-node-service
          servicePort: 8080